{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "clickhouse-connector.fullname" . }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx-external
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: ingress-nginx-external
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx-ip
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: ingress-nginx-ip
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: victoria-metrics
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: vmagent
    - from:
        - podSelector: {}
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
    - ports:
        - port: 53
          protocol: UDP
      to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
    - to:
        - podSelector: {}
{{- end }}