{
 "title": "Clickhouse connector exporter",
 "tags": [
  "clickhouse",
  "connector"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "HTTP RT",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(http_request_duration_seconds_count{handler=\"/api/v1/s2s/event\",code=\"200\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP RPS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_response_size_bytes_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection errors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clickhouse_connector_clickhouse_connecting_errors",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(clickhouse_connector_redis_connecting_errors))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server memory usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(go_memstats_alloc_bytes_total{pod=~\"clickhouse-connector-server.*\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer memory usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(go_memstats_alloc_bytes_total{pod=~\"clickhouse-connector-consumer.*\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall processed documents (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(clickhouse_connector_documents_processed[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis queue size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum by (queue) (rmq_ready)", "legendFormat": "{{queue}}" }
   ]
  },
  {
   "title": "Batches to DB per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "q" } },
   "targets": [
    {
     "expr": "sum by (batch_name) (increase(clickhouse_connector_batches_sent)) > 0",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Redis  rejected queue size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum by (queue) (rmq_rejected)", "legendFormat": "{{queue}}" }
   ]
  },
  {
   "title": "Batch size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (batch_name) (increase(clickhouse_connector_batch_size)) > 0",
     "legendFormat": "{{batch_name}}"
    }
   ]
  },
  {
   "title": "HTTP RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(http_response_size_bytes_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed documents by threads (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (consumer_name) (rate(clickhouse_connector_documents_processed[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP  AVG Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (code) (rate(http_request_duration_seconds_count{handler=\"/api/v1/s2s/event\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(clickhouse_connector_clickhouse_connecting_errors))",
     "legendFormat": "clickhouse_connecting_errors"
    },
    {
     "expr": "sum(increase(clickhouse_connector_redis_connecting_errors))",
     "legendFormat": "redis_connecting_errors"
    },
    {
     "expr": "sum(increase(clickhouse_connector_batches_appending_errors))",
     "legendFormat": "batches_appending_errors"
    },
    {
     "expr": "sum(increase(clickhouse_connector_batches_sending_errors))",
     "legendFormat": "batches_sending_errors"
    }
   ]
  }
 ]
}